-- H2 数据库初始化脚本（简化版）
-- 仅包含 API 测试所需的核心表

-- 关闭外键检查
SET FOREIGN_KEY_CHECKS = 0;

-- 系统岗位表
DROP TABLE IF EXISTS system_post;
CREATE TABLE system_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '岗位名称',
    code VARCHAR(50) NOT NULL COMMENT '岗位编码',
    description VARCHAR(255) COMMENT '岗位描述',
    status TINYINT DEFAULT 1 COMMENT '状态',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 系统用户表
DROP TABLE IF EXISTS system_user;
CREATE TABLE system_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(100) NOT NULL COMMENT '密码',
    name VARCHAR(50) COMMENT '姓名',
    type TINYINT DEFAULT 0 COMMENT '类型',
    phone VARCHAR(20) COMMENT '电话',
    avatar_url VARCHAR(255) COMMENT '头像',
    additional_info VARCHAR(500) COMMENT '附加信息',
    post_id BIGINT COMMENT '岗位ID',
    status TINYINT DEFAULT 1 COMMENT '状态',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 省份信息表
DROP TABLE IF EXISTS province_info;
CREATE TABLE province_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '省份名称',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 城市信息表
DROP TABLE IF EXISTS city_info;
CREATE TABLE city_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '城市名称',
    province_id BIGINT COMMENT '省份ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 区县信息表
DROP TABLE IF EXISTS district_info;
CREATE TABLE district_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '区县名称',
    city_id BIGINT COMMENT '城市ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 用户信息表
DROP TABLE IF EXISTS user_info;
CREATE TABLE user_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) COMMENT '手机号',
    password VARCHAR(100) COMMENT '密码',
    status TINYINT DEFAULT 1 COMMENT '状态',
    nickname VARCHAR(50) COMMENT '昵称',
    avatar_url VARCHAR(255) COMMENT '头像',
    openid VARCHAR(100) COMMENT '微信openid',
    unionid VARCHAR(100) COMMENT '微信unionid',
    mini_program_session_key VARCHAR(100) COMMENT '微信小程序session_key',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 属性key表
DROP TABLE IF EXISTS attr_key;
CREATE TABLE attr_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '属性名称',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 属性value表
DROP TABLE IF EXISTS attr_value;
CREATE TABLE attr_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '属性值',
    attr_key_id BIGINT COMMENT '属性keyID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 费用key表
DROP TABLE IF EXISTS fee_key;
CREATE TABLE fee_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '费用名称',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 费用value表
DROP TABLE IF EXISTS fee_value;
CREATE TABLE fee_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '费用值',
    unit VARCHAR(20) COMMENT '单位',
    fee_key_id BIGINT COMMENT '费用keyID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 支付方式表
DROP TABLE IF EXISTS payment_type;
CREATE TABLE payment_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '支付方式名称',
    pay_month_count INT COMMENT '支付月数',
    additional_info VARCHAR(200) COMMENT '附加信息',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 租期表
DROP TABLE IF EXISTS lease_term;
CREATE TABLE lease_term (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_count INT COMMENT '租期月数',
    unit VARCHAR(10) COMMENT '租期单位',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 配套设施表
DROP TABLE IF EXISTS facility_info;
CREATE TABLE facility_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TINYINT COMMENT '类型',
    name VARCHAR(50) NOT NULL COMMENT '设施名称',
    icon VARCHAR(100) COMMENT '图标',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 标签信息表
DROP TABLE IF EXISTS label_info;
CREATE TABLE label_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TINYINT COMMENT '类型',
    name VARCHAR(50) NOT NULL COMMENT '标签名称',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 公寓信息表
DROP TABLE IF EXISTS apartment_info;
CREATE TABLE apartment_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '公寓名称',
    introduction VARCHAR(500) COMMENT '简介',
    district_id BIGINT COMMENT '区县ID',
    district_name VARCHAR(50) COMMENT '区县名称',
    city_id BIGINT COMMENT '城市ID',
    city_name VARCHAR(50) COMMENT '城市名称',
    province_id BIGINT COMMENT '省份ID',
    province_name VARCHAR(50) COMMENT '省份名称',
    address_detail VARCHAR(200) COMMENT '详细地址',
    latitude VARCHAR(20) COMMENT '纬度',
    longitude VARCHAR(20) COMMENT '经度',
    phone VARCHAR(20) COMMENT '联系电话',
    is_release TINYINT DEFAULT 0 COMMENT '是否发布',
    avg_score DECIMAL(3,2) DEFAULT 5.00 COMMENT '平均评分',
    score_count INT DEFAULT 0 COMMENT '评分人数',
    status TINYINT DEFAULT 0 COMMENT '状态',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 房间信息表
DROP TABLE IF EXISTS room_info;
CREATE TABLE room_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_id BIGINT COMMENT '公寓ID',
    room_number VARCHAR(50) COMMENT '房间号',
    rent DECIMAL(10,2) COMMENT '租金',
    is_release TINYINT DEFAULT 0 COMMENT '是否发布',
    status TINYINT DEFAULT 0 COMMENT '状态',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 预约看房表
DROP TABLE IF EXISTS view_appointment;
CREATE TABLE view_appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT COMMENT '用户ID',
    name VARCHAR(50) COMMENT '用户姓名',
    phone VARCHAR(20) COMMENT '用户手机号码',
    apartment_id BIGINT COMMENT '公寓ID',
    appointment_time TIMESTAMP COMMENT '预约时间',
    additional_info VARCHAR(500) COMMENT '备注信息',
    appointment_status TINYINT DEFAULT 0 COMMENT '预约状态',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 租约表
DROP TABLE IF EXISTS lease_agreement;
CREATE TABLE lease_agreement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) COMMENT '承租人手机号码',
    name VARCHAR(50) COMMENT '承租人姓名',
    identification_number VARCHAR(18) COMMENT '承租人身份证号码',
    user_id BIGINT COMMENT '用户ID',
    apartment_id BIGINT COMMENT '公寓ID',
    room_id BIGINT COMMENT '房间ID',
    lease_start_date DATE COMMENT '租期开始日期',
    lease_end_date DATE COMMENT '租期结束日期',
    lease_term_id BIGINT COMMENT '租期id',
    rent DECIMAL(10,2) COMMENT '租金',
    deposit DECIMAL(10,2) COMMENT '押金',
    payment_type_id BIGINT COMMENT '支付类型id',
    status TINYINT DEFAULT 0 COMMENT '状态',
    source_type TINYINT COMMENT '租约来源',
    additional_info VARCHAR(500) COMMENT '备注信息',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 公寓配套设施关联表
DROP TABLE IF EXISTS apartment_facility;
CREATE TABLE apartment_facility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_id BIGINT COMMENT '公寓ID',
    facility_id BIGINT COMMENT '设施ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 公寓标签关联表
DROP TABLE IF EXISTS apartment_label;
CREATE TABLE apartment_label (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_id BIGINT COMMENT '公寓ID',
    label_id BIGINT COMMENT '标签ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 公寓费用关联表
DROP TABLE IF EXISTS apartment_fee_value;
CREATE TABLE apartment_fee_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartment_id BIGINT COMMENT '公寓ID',
    fee_value_id BIGINT COMMENT '费用valueID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 房间配套设施关联表
DROP TABLE IF EXISTS room_facility;
CREATE TABLE room_facility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT COMMENT '房间ID',
    facility_id BIGINT COMMENT '设施ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 房间标签关联表
DROP TABLE IF EXISTS room_label;
CREATE TABLE room_label (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT COMMENT '房间ID',
    label_id BIGINT COMMENT '标签ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 房间支付方式关联表
DROP TABLE IF EXISTS room_payment_type;
CREATE TABLE room_payment_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT COMMENT '房间ID',
    payment_type_id BIGINT COMMENT '支付方式ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 房间租期关联表
DROP TABLE IF EXISTS room_lease_term;
CREATE TABLE room_lease_term (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT COMMENT '房间ID',
    lease_term_id BIGINT COMMENT '租期ID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 房间属性关联表
DROP TABLE IF EXISTS room_attr_value;
CREATE TABLE room_attr_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT COMMENT '房间ID',
    attr_value_id BIGINT COMMENT '属性valueID',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 用户行为日志表
DROP TABLE IF EXISTS user_behavior_log;
CREATE TABLE user_behavior_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT COMMENT '用户ID',
    behavior_type TINYINT NOT NULL COMMENT '行为类型：1-浏览 2-搜索 3-收藏 4-预约 5-分享 6-登录 7-点击 8-提交 9-咨询 10-签约',
    behavior_desc VARCHAR(100) COMMENT '行为描述',
    target_type VARCHAR(50) COMMENT '目标类型',
    target_id BIGINT COMMENT '目标ID',
    request_url VARCHAR(255) COMMENT '请求URL',
    request_param VARCHAR(2000) COMMENT '请求参数',
    user_ip VARCHAR(50) COMMENT '用户IP',
    user_agent VARCHAR(500) COMMENT '用户代理',
    device_type VARCHAR(20) COMMENT '设备类型',
    source_page VARCHAR(255) COMMENT '来源页面',
    behavior_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '行为时间',
    extra_data VARCHAR(1000) COMMENT '额外数据(JSON)',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 公寓评分记录表
DROP TABLE IF EXISTS apartment_rating;
CREATE TABLE apartment_rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT COMMENT '用户ID',
    apartment_id BIGINT COMMENT '公寓ID',
    environment_score DECIMAL(3,2) COMMENT '环境评分(1-5)',
    traffic_score DECIMAL(3,2) COMMENT '交通评分(1-5)',
    facility_score DECIMAL(3,2) COMMENT '设施评分(1-5)',
    service_score DECIMAL(3,2) COMMENT '服务评分(1-5)',
    value_score DECIMAL(3,2) COMMENT '性价比评分(1-5)',
    overall_score DECIMAL(3,2) COMMENT '综合评分(1-5)',
    content VARCHAR(500) COMMENT '评分内容',
    is_anonymous TINYINT DEFAULT 0 COMMENT '是否匿名(0-否 1-是)',
    status TINYINT DEFAULT 1 COMMENT '状态(0-待审核 1-已通过 2-已拒绝)',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 浏览历史表
DROP TABLE IF EXISTS browsing_history;
CREATE TABLE browsing_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT COMMENT '用户ID',
    room_id BIGINT COMMENT '房间ID',
    browse_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '浏览时间',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 图片信息表
DROP TABLE IF EXISTS graph_info;
CREATE TABLE graph_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) COMMENT '图片名称',
    item_type TINYINT COMMENT '所属对象类型：1-公寓 2-房间',
    item_id BIGINT COMMENT '所属对象ID',
    url VARCHAR(500) COMMENT '图片URL',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 开启外键检查
SET FOREIGN_KEY_CHECKS = 1;

-- 后台操作日志表
DROP TABLE IF EXISTS system_operation_log;
CREATE TABLE system_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) COMMENT '模块标题',
    business_type TINYINT DEFAULT 0 COMMENT '业务类型：0-其他 1-新增 2-修改 3-删除 4-查询 5-导出 6-导入 7-登录 8-登出 9-强退 10-清空 11-审批 12-驳回 13-取消 14-启用 15-禁用 16-分配 17-重置密码 18-上传 19-下载',
    method VARCHAR(500) COMMENT '方法名称',
    request_method VARCHAR(10) COMMENT '请求方式',
    operator_type TINYINT DEFAULT 1 COMMENT '操作者类型：0-其他 1-后台用户 2-移动端用户 3-系统',
    oper_name VARCHAR(50) COMMENT '操作人员',
    user_id BIGINT COMMENT '用户ID',
    oper_url VARCHAR(500) COMMENT '请求URL',
    oper_ip VARCHAR(50) COMMENT '主机地址',
    oper_param TEXT COMMENT '请求参数',
    json_result TEXT COMMENT '返回参数',
    status TINYINT DEFAULT 1 COMMENT '操作状态（0-失败 1-成功）',
    error_msg VARCHAR(2000) COMMENT '错误消息',
    oper_time TIMESTAMP COMMENT '操作时间',
    cost_time BIGINT COMMENT '执行耗时（毫秒）',
    operation_desc VARCHAR(500) COMMENT '操作描述',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 后台登录日志表
DROP TABLE IF EXISTS system_login_log;
CREATE TABLE system_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) COMMENT '用户名',
    ip_addr VARCHAR(50) COMMENT '登录IP地址',
    login_location VARCHAR(100) COMMENT '登录地点',
    browser VARCHAR(50) COMMENT '浏览器类型',
    os VARCHAR(50) COMMENT '操作系统',
    status TINYINT DEFAULT 1 COMMENT '登录状态（0-失败 1-成功）',
    msg VARCHAR(255) COMMENT '提示消息',
    login_time TIMESTAMP COMMENT '登录时间',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);

-- 后台操作日志表
DROP TABLE IF EXISTS system_operation_log;
CREATE TABLE system_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) COMMENT '模块标题',
    business_type TINYINT DEFAULT 0 COMMENT '业务类型：0-其他 1-新增 2-修改 3-删除 4-查询 5-导出 6-导入 7-登录 8-登出',
    method VARCHAR(500) COMMENT '方法名称',
    request_method VARCHAR(10) COMMENT '请求方式',
    operator_type TINYINT DEFAULT 1 COMMENT '操作类别：0-其他 1-后台用户 2-移动端用户 3-系统',
    oper_name VARCHAR(50) COMMENT '操作人员',
    user_id BIGINT COMMENT '用户ID',
    oper_url VARCHAR(255) COMMENT '请求URL',
    oper_ip VARCHAR(50) COMMENT '主机地址',
    oper_param VARCHAR(2000) COMMENT '请求参数',
    json_result VARCHAR(2000) COMMENT '返回参数',
    status TINYINT DEFAULT 1 COMMENT '操作状态：0-异常 1-正常',
    error_msg VARCHAR(2000) COMMENT '错误消息',
    oper_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    cost_time BIGINT COMMENT '执行耗时（毫秒）',
    operation_desc VARCHAR(255) COMMENT '操作描述',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '是否删除'
);
